-- Persists OAuth2 refresh tokens so services that use rotating tokens
-- (e.g. saxo_stream) survive restarts without manual re-authentication.
--
-- Saxo's OAuth2 refresh tokens rotate on each use (RFC 6749 §10.4).
-- A plain ExternalSecret (Vault → k8s Secret) is pull-once-at-pod-start
-- and cannot be updated by the running service. Without write-back, a pod
-- restart would require manual Vault intervention to inject the latest token.
--
-- Write-back flow:
--   1. Pod starts → reads latest refresh_token WHERE source = 'saxo'.
--   2. Service uses refresh_token to obtain a new access_token from Saxo.
--   3. Saxo returns a new refresh_token → service upserts it here.
--   4. On next restart the cycle continues without manual intervention.
--
-- `source` identifies which OAuth provider a row represents ("saxo" today).
-- `refresh_token_expires_at` is stored alongside each rotation so the service
-- can detect expiry and prompt for re-authentication before it lapses.

CREATE TABLE IF NOT EXISTS oauth_tokens (
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source                      TEXT        NOT NULL,
    refresh_token               TEXT        NOT NULL,
    refresh_token_expires_at    TIMESTAMPTZ,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT oauth_tokens_source_key UNIQUE (source)
);
