apiVersion: batch/v1
kind: CronJob
metadata:
  name: earnings
  labels:
    app: earnings
spec:
  schedule: {{ .Values.schedules.earnings | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: earnings
        spec:
          restartPolicy: OnFailure
          containers:
            - name: earnings
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              command: ["/usr/local/bin/earnings"]
              envFrom:
                - secretRef:
                    name: chronicle-secret
              resources:
                requests:
                  memory: {{ .Values.resources.requests.memory | quote }}
                  cpu: {{ .Values.resources.requests.cpu | quote }}
                limits:
                  memory: {{ .Values.resources.limits.memory | quote }}
