apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saxo-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore

  target:
    name: saxo-secret
    creationPolicy: Owner

  data:
    - secretKey: SAXO_ACCESS_TOKEN
      remoteRef:
        key: nexus/saxo
        property: access_token

    - secretKey: SAXO_TOKEN_EXPIRES_AT
      remoteRef:
        key: nexus/saxo
        property: token_expires_at

    - secretKey: SAXO_API_BASE
      remoteRef:
        key: nexus/saxo
        property: api_base

    - secretKey: SAXO_STREAMING_BASE
      remoteRef:
        key: nexus/saxo
        property: streaming_base
