apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chronicle-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore

  target:
    name: chronicle-secret
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexus/chronicle
        property: DATABASE_URL

    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: nexus/chronicle
        property: KAFKA_BROKERS

    - secretKey: KAFKA_TOPIC
      remoteRef:
        key: nexus/chronicle
        property: KAFKA_TOPIC

    - secretKey: KAFKA_GROUP_ID
      remoteRef:
        key: nexus/chronicle
        property: KAFKA_GROUP_ID
