apiVersion: v1
kind: Service
metadata:
  name: saxo-stream
  labels:
    app: saxo-stream
spec:
  type: NodePort
  selector:
    app: saxo-stream
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32080
