apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insight-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore
  target:
    name: insight-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexus/insight
        property: DATABASE_URL
