{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: insight
  labels:
    app: insight
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: insight
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}
