apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signal-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore

  target:
    name: signal-secret
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: signal
        property: DATABASE_URL

    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: signal
        property: KAFKA_BROKERS

    - secretKey: POLYGON_API_KEY
      remoteRef:
        key: signal
        property: POLYGON_API_KEY

    - secretKey: KAFKA_GROUP_ID
      remoteRef:
        key: signal
        property: KAFKA_GROUP_ID

    - secretKey: KAFKA_TOPIC
      remoteRef:
        key: signal
        property: KAFKA_TOPIC

    - secretKey: KAFKA_TICKERS_TOPIC
      remoteRef:
        key: signal
        property: KAFKA_TICKERS_TOPIC
