-- Generalizes `saxo_tokens` into `oauth_tokens`: adds a semantically
-- meaningful `source` key alongside the existing `id` primary key, and the
-- refresh token's own expiry timestamp (needed to persist alongside each
-- rotation — see PgTokenStore::save in chronicle/src/saxo_stream.rs).
--
-- `source` identifies which OAuth token a row represents ("saxo" today).
-- The table is renamed since it's no longer necessarily Saxo-only — `id`
-- remains the primary key; `source` gets its own UNIQUE constraint so
-- queries/upserts can target it directly (`WHERE source = 'saxo'`,
-- `ON CONFLICT (source)`) instead of the previously-hardcoded `id = 1`.
-- The old `CHECK (id = 1)` is dropped and `id` becomes a proper
-- auto-incrementing surrogate key, since the table can now hold more than
-- one row (e.g. a second broker or environment) without another redesign.

ALTER TABLE saxo_tokens
    ADD COLUMN source TEXT,
    ADD COLUMN refresh_token_expires_at TIMESTAMPTZ;

UPDATE saxo_tokens SET source = 'saxo' WHERE source IS NULL;

ALTER TABLE saxo_tokens
    ALTER COLUMN source SET NOT NULL,
    ADD CONSTRAINT saxo_tokens_source_key UNIQUE (source),
    DROP CONSTRAINT IF EXISTS saxo_tokens_id_check;

ALTER TABLE saxo_tokens ALTER COLUMN id DROP DEFAULT;
ALTER TABLE saxo_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE saxo_tokens RENAME TO oauth_tokens;
ALTER TABLE oauth_tokens RENAME CONSTRAINT saxo_tokens_source_key TO oauth_tokens_source_key;
