apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: nexus/grafana
        property: GF_SECURITY_ADMIN_USER

    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: nexus/grafana
        property: GF_SECURITY_ADMIN_PASSWORD

    - secretKey: GF_DATABASE_PASSWORD
      remoteRef:
        key: nexus/grafana
        property: GF_DATABASE_PASSWORD
