apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-secret
    creationPolicy: Owner
  data:
    - secretKey: git.user
      remoteRef:
        key: nexus/github
        property: username

    - secretKey: git.password
      remoteRef:
        key: nexus/github
        property: token
