apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-secret-store
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Owner
  data:
    - secretKey: githubAppID
      remoteRef:
        key: nexus/github-app
        property: app_id

    - secretKey: githubAppInstallationID
      remoteRef:
        key: nexus/github-app
        property: installation_id

    - secretKey: githubAppPrivateKey
      remoteRef:
        key: nexus/github-app
        property: private_key
