apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: nexus-services
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: semver
  applicationRefs:
    - namePattern: "signal-signal"
      images:
        - alias: nexus
          imageName: lmapwns/nexus
          manifestTargets:
            helm:
              tag: image.tag
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/lassemand/nexus.git
          branch: main
          writeBackTarget: helmvalues:./values.yaml
          credentials: secret:argocd/git-creds#githubAppID,githubAppInstallationID,githubAppPrivateKey
    - namePattern: "chronicle-chronicle"
      images:
        - alias: nexus
          imageName: lmapwns/nexus
          manifestTargets:
            helm:
              tag: image.tag
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/lassemand/nexus.git
          branch: main
          writeBackTarget: helmvalues:./values.yaml
          credentials: secret:argocd/git-creds#githubAppID,githubAppInstallationID,githubAppPrivateKey
    - namePattern: "market-market"
      images:
        - alias: nexus
          imageName: lmapwns/nexus
          manifestTargets:
            helm:
              tag: image.tag
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/lassemand/nexus.git
          branch: main
          writeBackTarget: helmvalues:./values.yaml
          credentials: secret:argocd/git-creds#githubAppID,githubAppInstallationID,githubAppPrivateKey
    - namePattern: "insight-insight"
      images:
        - alias: nexus
          imageName: lmapwns/nexus
          manifestTargets:
            helm:
              tag: image.tag
      writeBackConfig:
        method: git
        gitConfig:
          repository: https://github.com/lassemand/nexus.git
          branch: main
          writeBackTarget: helmvalues:./values.yaml
          credentials: secret:argocd/git-creds#githubAppID,githubAppInstallationID,githubAppPrivateKey
