image:
  repository: "lmapwns/nexus"  # TODO: replace with real Docker Hub username/image
  tag: "latest"

replicaCount: 1

service:
  enabled: true

resources:
  requests:
    memory: "64Mi"
    cpu: "25m"
