apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-chronicle
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    nexus/chart: chronicle
spec:
  project: default

  source:
    repoURL: https://github.com/lassemand/nexus.git
    targetRevision: main
    path: infra/charts/chronicle
    helm:
      releaseName: chronicle
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: chronicle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
