// Public API items are used by the CLI subcommand wiring task, which is not yet
// implemented. Suppress dead_code until that task lands.
#![allow(dead_code)]

//! One-shot local OAuth2 callback listener for the Saxo authorization-code flow.
//!
//! Saxo's authorization server redirects the user's browser to a registered
//! `redirect_uri` (e.g. `http://localhost:7878/callback`) carrying the
//! one-time authorization `code` and the CSRF `state` token.  This module
//! binds a temporary TCP listener, catches that single request, delivers a
//! confirmation page to the browser, then exits cleanly — leaving the port
//! free for the next run.

use std::time::Duration;
use thiserror::Error;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::net::TcpListener;

/// Default local port for the OAuth callback listener.
///
/// Must match the `redirect_uri` registered in the Saxo developer portal
/// (e.g. `http://localhost:7878/callback`).
// Not yet referenced by a CLI subcommand — will be used in the
// subcommand-wiring task.
#[allow(dead_code)]
pub const DEFAULT_CALLBACK_PORT: u16 = 7878;

/// Default timeout in seconds to wait for the browser callback.
///
/// If the user does not complete the authorization flow within this window,
/// [`await_callback`] returns [`CallbackError::Timeout`].
// Not yet referenced by a CLI subcommand — will be used in the
// subcommand-wiring task.
#[allow(dead_code)]
pub const DEFAULT_CALLBACK_TIMEOUT_SECS: u64 = 120;

/// Query parameters extracted from the OAuth2 authorization-server redirect.
///
/// All fields are optional at the parse level — semantic validation (e.g.
/// checking that `code` is present, or that `state` matches the expected
/// CSRF token) is the caller's responsibility.
#[derive(Debug, Clone, Default)]
pub struct CallbackParams {
    /// The one-time authorization code to exchange for tokens. Present on success.
    pub code: Option<String>,
    /// The CSRF state token echoed back by the authorization server.
    /// Must be compared against the value generated by
    /// [`alpha::saxo::auth::generate_state`] before proceeding.
    pub state: Option<String>,
    /// OAuth2 error code when the user denies access (e.g. `"access_denied"`).
    pub error: Option<String>,
    /// Human-readable error description accompanying [`error`](Self::error).
    pub error_description: Option<String>,
}

/// Errors returned by [`await_callback`].
#[derive(Debug, Error)]
pub enum CallbackError {
    /// The TCP listener could not be bound to the requested port.
    ///
    /// Most likely cause: the port is already in use by another process.
    /// Check with `lsof -i :{port}` or change the port via the CLI flag.
    #[error("could not bind to port {port}: {source}")]
    Bind {
        port: u16,
        #[source]
        source: std::io::Error,
    },
    /// No browser callback arrived within the configured timeout.
    #[error("timed out after {secs}s waiting for the OAuth callback on port {port}")]
    Timeout { port: u16, secs: u64 },
    /// An I/O error occurred while reading or writing the callback connection.
    #[error("I/O error handling the OAuth callback connection: {0}")]
    Io(std::io::Error),
}

/// Wait for exactly one OAuth2 callback on `http://127.0.0.1:{port}/callback`.
///
/// Binds a `TcpListener` on `127.0.0.1:{port}`, waits up to `timeout_secs`
/// seconds for the browser to deliver the authorization-server redirect, then:
///
/// 1. Parses `code`, `state`, `error`, and `error_description` from the
///    request's query string.
/// 2. Sends a minimal HTML confirmation page so the user sees feedback in
///    the browser before closing the tab.
/// 3. Returns [`CallbackParams`] and drops the listener — the port is free
///    immediately after this call completes.
///
/// # Errors
///
/// - [`CallbackError::Bind`] — port already in use or insufficient permissions.
/// - [`CallbackError::Timeout`] — no request arrived within `timeout_secs`.
/// - [`CallbackError::Io`] — I/O error while reading/writing the connection.
///
/// # Port and redirect URI
///
/// The `port` **must** match the `redirect_uri` you registered in the Saxo
/// developer portal. The default is [`DEFAULT_CALLBACK_PORT`] (7878), giving
/// a redirect URI of `http://localhost:7878/callback`.
pub async fn await_callback(port: u16, timeout_secs: u64) -> Result<CallbackParams, CallbackError> {
    let listener = TcpListener::bind(("127.0.0.1", port))
        .await
        .map_err(|e| CallbackError::Bind { port, source: e })?;

    let (stream, _addr) =
        tokio::time::timeout(Duration::from_secs(timeout_secs), listener.accept())
            .await
            .map_err(|_| CallbackError::Timeout {
                port,
                secs: timeout_secs,
            })?
            .map_err(CallbackError::Io)?;

    let (read_half, mut write_half) = stream.into_split();
    let mut reader = BufReader::new(read_half);

    // First line of the HTTP request: `GET /callback?code=...&state=... HTTP/1.1`
    let mut request_line = String::new();
    reader
        .read_line(&mut request_line)
        .await
        .map_err(CallbackError::Io)?;

    let params = parse_query_from_request_line(&request_line);

    // Drain remaining request headers so the browser does not see a connection reset.
    loop {
        let mut line = String::new();
        reader
            .read_line(&mut line)
            .await
            .map_err(CallbackError::Io)?;
        if line.trim().is_empty() {
            break;
        }
    }

    // Deliver a confirmation page — the user is looking at a browser tab.
    const BODY: &str = "<!DOCTYPE html>\
        <html lang=\"en\">\
        <head><meta charset=\"utf-8\"><title>Authorization received</title></head>\
        <body>\
        <h1>Authorization received</h1>\
        <p>You can close this tab and return to the terminal.</p>\
        </body></html>";

    let response = format!(
        "HTTP/1.1 200 OK\r\n\
         Content-Type: text/html; charset=utf-8\r\n\
         Content-Length: {len}\r\n\
         Connection: close\r\n\
         \r\n\
         {BODY}",
        len = BODY.len(),
    );
    write_half
        .write_all(response.as_bytes())
        .await
        .map_err(CallbackError::Io)?;
    write_half.flush().await.map_err(CallbackError::Io)?;

    Ok(params)
}

/// Parse `code`, `state`, `error`, and `error_description` from an HTTP/1.x
/// request line such as `GET /callback?code=ABC&state=XYZ HTTP/1.1`.
///
/// Returns a [`CallbackParams`] with all absent fields as `None`.
fn parse_query_from_request_line(request_line: &str) -> CallbackParams {
    let query = request_line
        .split_whitespace()
        .nth(1)
        .and_then(|path_query| path_query.split_once('?'))
        .map(|(_, q)| q)
        .unwrap_or("");

    let mut params = CallbackParams::default();
    for pair in query.split('&') {
        let Some((key, raw_value)) = pair.split_once('=') else {
            continue;
        };
        let value = percent_decode(raw_value);
        match key {
            "code" => params.code = Some(value),
            "state" => params.state = Some(value),
            "error" => params.error = Some(value),
            "error_description" => params.error_description = Some(value),
            _ => {}
        }
    }
    params
}

/// Minimal percent-decoding for OAuth2 query values.
///
/// Decodes `%XX` sequences (hex byte) and `+` (space). Sufficient for the
/// ASCII-safe parameter values returned by Saxo's authorization server.
fn percent_decode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let Ok(byte) = u8::from_str_radix(&s[i + 1..i + 3], 16) {
                out.push(byte as char);
                i += 3;
                continue;
            }
        }
        out.push(if bytes[i] == b'+' {
            ' '
        } else {
            bytes[i] as char
        });
        i += 1;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── parse_query_from_request_line ─────────────────────────────────────

    #[test]
    fn parse_success_params() {
        let line = "GET /callback?code=AUTH123&state=deadbeef HTTP/1.1\r\n";
        let p = parse_query_from_request_line(line);
        assert_eq!(p.code.as_deref(), Some("AUTH123"));
        assert_eq!(p.state.as_deref(), Some("deadbeef"));
        assert!(p.error.is_none());
        assert!(p.error_description.is_none());
    }

    #[test]
    fn parse_error_denial_params() {
        let line =
            "GET /callback?error=access_denied&error_description=User+denied+access HTTP/1.1\r\n";
        let p = parse_query_from_request_line(line);
        assert!(p.code.is_none());
        assert_eq!(p.error.as_deref(), Some("access_denied"));
        assert_eq!(p.error_description.as_deref(), Some("User denied access"));
    }

    #[test]
    fn parse_no_query_string_returns_all_none() {
        let p = parse_query_from_request_line("GET /callback HTTP/1.1\r\n");
        assert!(p.code.is_none());
        assert!(p.state.is_none());
        assert!(p.error.is_none());
    }

    #[test]
    fn parse_empty_request_line_returns_all_none() {
        let p = parse_query_from_request_line("");
        assert!(p.code.is_none());
    }

    #[test]
    fn parse_unknown_params_are_ignored() {
        let line = "GET /callback?code=X&unknown=foo&state=Y HTTP/1.1\r\n";
        let p = parse_query_from_request_line(line);
        assert_eq!(p.code.as_deref(), Some("X"));
        assert_eq!(p.state.as_deref(), Some("Y"));
    }

    // ── percent_decode ────────────────────────────────────────────────────

    #[test]
    fn percent_decode_hex_sequences() {
        assert_eq!(percent_decode("hello%20world"), "hello world");
        assert_eq!(percent_decode("foo%2Bbar"), "foo+bar");
        assert_eq!(percent_decode("a%3Db"), "a=b");
    }

    #[test]
    fn percent_decode_plus_as_space() {
        assert_eq!(percent_decode("hello+world"), "hello world");
    }

    #[test]
    fn percent_decode_passthrough() {
        assert_eq!(percent_decode("plain"), "plain");
        assert_eq!(percent_decode(""), "");
    }

    #[test]
    fn percent_decode_invalid_percent_passes_through() {
        assert_eq!(percent_decode("%GG"), "%GG");
    }

    // ── await_callback integration tests (loopback) ───────────────────────

    #[tokio::test]
    async fn await_callback_returns_params_on_connection() {
        use tokio::io::AsyncWriteExt;
        use tokio::net::TcpStream;

        let port = 19871u16;

        let listener_task = tokio::spawn(await_callback(port, 5));
        // Give the listener a moment to bind before connecting.
        tokio::time::sleep(Duration::from_millis(20)).await;

        let mut conn = TcpStream::connect(("127.0.0.1", port)).await.unwrap();
        conn.write_all(
            b"GET /callback?code=TESTCODE&state=TESTSTATE HTTP/1.1\r\n\
              Host: localhost\r\n\
              \r\n",
        )
        .await
        .unwrap();

        let result = listener_task
            .await
            .unwrap()
            .expect("listener should succeed");
        assert_eq!(result.code.as_deref(), Some("TESTCODE"));
        assert_eq!(result.state.as_deref(), Some("TESTSTATE"));
        assert!(result.error.is_none());
    }

    #[tokio::test]
    async fn await_callback_times_out() {
        // Use a 1-second timeout so the test suite doesn't stall.
        let result = await_callback(19872, 1).await;
        assert!(
            matches!(result, Err(CallbackError::Timeout { .. })),
            "expected Timeout, got: {result:?}"
        );
    }

    #[tokio::test]
    async fn await_callback_bind_fails_on_used_port() {
        let port = 19873u16;
        // Hold the port so await_callback cannot bind it.
        let _occupied = TcpListener::bind(("127.0.0.1", port)).await.unwrap();

        let result = await_callback(port, 5).await;
        assert!(
            matches!(result, Err(CallbackError::Bind { .. })),
            "expected Bind error, got: {result:?}"
        );
    }
}
