apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insider-model
  namespace: signal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
