apiVersion: v2
name: grafana
description: Umbrella chart for Grafana with Postgres and Prometheus datasources.
type: application
version: 0.1.0
appVersion: "12.3.1"
dependencies:
  - name: grafana
    version: "10.5.15"
    repository: https://grafana.github.io/helm-charts
